export const ThemeTokens = {
  colors: {
    background: '#fff8f5',
    surface: '#fff8f5',
    surfaceContainerLow: '#fbf2ed',
    surfaceContainer: '#f5ece7',
    surfaceContainerHigh: '#efe6e2',
    surfaceContainerLowest: '#ffffff',
    primary: '#412817',
    onPrimary: '#ffffff',
    primaryContainer: '#5a3e2b',
    onPrimaryContainer: '#d1aa91',
    secondary: '#934b19',
    onSecondary: '#ffffff',
    onSurface: '#1e1b18',
    onSurfaceVariant: '#50453e',
    outline: '#82746d',
    outlineVariant: '#d3c3bb',
    error: '#ba1a1a',
    onError: '#ffffff',
  },
  borderRadius: {
    sm: 4,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  shadows: {
    soft: {
      shadowColor: '#5a3e2b',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 4,
    },
  },
} as const;
